export type ComponentCategory =
  | "auth"
  | "marketing"
  | "data"
  | "commerce"
  | "files"
  | "content"
  | "api"
  | "forms"
  | "hero"
  | "saas"
  | "productivity"
  | "team"
  | "documents"
  | "animation";

export type ComponentSource =
  | "JB"
  | "21st.dev"
  | "shadcnblocks"
  | "shadcn-space"
  | "ncdai"
  | "magicui"
  | "external";

export type JBComponent = {
  slug: string;
  name: string;
  tagline: string;
  category: ComponentCategory;
  categoryLabel: string;
  install: string;
  blogUrl?: string;
  source?: ComponentSource;
  sourceLabel?: string;
  prerequisites?: string[];
  envVars?: { name: string; description: string }[];
  features: string[];
  whenToUse: string;
  whenNotToUse: string;
  filesAdded?: string[];
};

export const components: JBComponent[] = [
  {
    slug: "better-auth-ui",
    name: "JB Better Auth UI",
    tagline: "Production-ready authentication — sign-in, sign-up, OAuth, password reset.",
    category: "auth",
    categoryLabel: "Authentication",
    install: "pnpm dlx shadcn@latest add https://better-auth-ui.desishub.com/r/auth-components.json",
    blogUrl: "https://jb.desishub.com/components/jb-better-auth-ui-components",
    prerequisites: ["Next.js 16 + shadcn/ui", "PostgreSQL (Neon / Supabase)", "Resend account"],
    envVars: [
      { name: "BETTER_AUTH_SECRET", description: "Random 32+ char string" },
      { name: "BETTER_AUTH_URL", description: "Full app URL (e.g. http://localhost:3000)" },
      { name: "DATABASE_URL", description: "PostgreSQL connection string" },
      { name: "RESEND_FROM_EMAIL", description: "Verified sender (e.g. noreply@yourdomain.com)" },
      { name: "RESEND_API_KEY", description: "From Resend dashboard" },
      { name: "GOOGLE_CLIENT_ID", description: "Optional — Google OAuth" },
      { name: "GOOGLE_CLIENT_SECRET", description: "Optional — Google OAuth" },
      { name: "GITHUB_CLIENT_ID", description: "Optional — GitHub OAuth" },
      { name: "GITHUB_CLIENT_SECRET", description: "Optional — GitHub OAuth" },
    ],
    features: [
      "8 auth components (SignIn, SignUp, VerifyEmail, ForgetPassword, ResetPassword, ChangePassword, Profile, LogoutButton)",
      "OTP-based email verification and password reset",
      "Includes Prisma schema, validation schemas, API route handlers",
      "OAuth integration with Google and GitHub",
      "Email templates and env var configuration",
    ],
    whenToUse: "Every project that needs authentication. This is the default auth solution.",
    whenNotToUse: "Non-PostgreSQL databases, or projects needing custom auth logic outside this structure.",
    filesAdded: [
      "/auth/sign-in",
      "/auth/sign-up",
      "/auth/verify-email",
      "/auth/forgot-password",
      "/auth/reset-password",
      "/auth/change-password",
      "/auth/profile",
      "/dashboard",
      "/api/auth/[...all]/route.ts",
      "Prisma schema additions",
    ],
  },
  {
    slug: "website-ui",
    name: "Website UI",
    tagline: "Complete Next.js marketing scaffold — landing, pricing, docs, and more.",
    category: "marketing",
    categoryLabel: "Marketing",
    install: "pnpm dlx shadcn@latest add https://ui-components.desishub.com/r/website-ui.json",
    blogUrl: "https://jb.desishub.com/components/website-ui-component",
    prerequisites: ["Initialized Next.js project"],
    features: [
      "10 pre-built pages (home, pricing, docs, changelog, developers, help, contact, hire-expert, 404)",
      "Responsive navbar with dark mode toggle and language switcher",
      "Built-in i18n via next-intl (EN/FR translations)",
      "SEO features: OpenGraph, Twitter cards, sitemap.xml, robots.txt",
      "Auto-installs next-intl, lucide-react, class-variance-authority, clsx, tailwind-merge",
    ],
    whenToUse: "SaaS landing pages, startup websites, portfolios, product docs, agency templates, OSS homepages.",
    whenNotToUse: "Projects needing highly custom layouts from scratch or non-standard content structures.",
    filesAdded: [
      "/, /pricing, /docs, /developers, /help, /contact, /hire-expert, /404",
      "components/navbar.tsx, footer.tsx, structured-data.tsx",
      "config/site.ts, i18n/request.ts",
      "messages/en.json, messages/fr.json",
    ],
  },
  {
    slug: "stripe-ui",
    name: "Stripe UI",
    tagline: "Production-ready Stripe checkout with Payment Element + order management.",
    category: "commerce",
    categoryLabel: "Commerce",
    install: "pnpm dlx shadcn@latest add https://stripe-ui-component.desishub.com/r/stripe-ui-component.json",
    blogUrl: "https://jb.desishub.com/components/stripe-ui-component",
    prerequisites: [
      "shadcn/ui initialized",
      "JB Better Auth UI installed",
      "Zustand Cart installed",
      "PostgreSQL database",
      "Stripe API keys",
    ],
    envVars: [
      { name: "STRIPE_SECRET_KEY", description: "Server-side key (sk_test_ or sk_live_)" },
      { name: "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY", description: "Client-side key (pk_test_ or pk_live_)" },
    ],
    features: [
      "Embedded Stripe Payment Element with multi-method support and 3D Secure",
      "Complete checkout: order summary, shipping, payment processing",
      "Order management with history tracking and verification",
      "Server-side API routes for secure payment intent creation",
      "Responsive product grid integrated with Zustand cart",
    ],
    whenToUse: "E-commerce platforms, SaaS payment systems, digital product stores needing full Stripe checkout flows.",
    whenNotToUse: "Simple donations, subscription-only products (use Stripe subscriptions directly), or markets needing Mobile Money (use DGateway).",
    filesAdded: [
      "/products, /checkout, /order-confirmation, /dashboard/orders, /dashboard/orders/[id]",
      "/api/stripe/create-payment-intent, /api/stripe/verify-payment",
      "Prisma: Category, Product, Order, OrderItem models",
    ],
  },
  {
    slug: "data-table",
    name: "Data Table",
    tagline: "TanStack-powered table with search, sort, pagination, column visibility.",
    category: "data",
    categoryLabel: "Data",
    install: "pnpm dlx shadcn@latest add https://jb.desishub.com/r/data-table.json",
    blogUrl: "https://jb.desishub.com/components/data-table-component",
    prerequisites: ["TanStack React Table", "shadcn/ui"],
    features: [
      "Search and filter table data",
      "Column sorting with directional indicators",
      "Pagination for large datasets",
      "Toggleable column visibility preferences",
      "Row selection functionality",
      "Pre-built column helpers (SortableColumn, DateColumn, ImageColumn, StatusColumn, ActionColumn)",
    ],
    whenToUse: "Any page displaying lists of records (users, orders, products, invoices, contacts). Default table for dashboards.",
    whenNotToUse: "Simple static tables (under 5 rows) or non-interactive data displays.",
    filesAdded: ["data-table.tsx + column helpers (location depends on shadcn install target)"],
  },
  {
    slug: "file-storage",
    name: "File Storage UI",
    tagline: "Drag-drop file uploads with S3 + R2 support, presigned URLs, and management.",
    category: "files",
    categoryLabel: "File storage",
    install: "pnpm dlx shadcn@latest add https://file-storage.desishub.com/r/file-storage.json",
    blogUrl: "https://jb.desishub.com/components/file-storage-ui",
    prerequisites: [
      "Next.js with shadcn/ui",
      "Prisma ORM",
      "AWS S3 OR Cloudflare R2 bucket with credentials",
    ],
    envVars: [
      { name: "DATABASE_URL", description: "Database connection string" },
      { name: "AWS_S3_REGION", description: "Required if using S3" },
      { name: "AWS_S3_BUCKET_NAME", description: "Required if using S3" },
      { name: "AWS_S3_ACCESS_KEY_ID", description: "Required if using S3" },
      { name: "AWS_S3_SECRET_ACCESS_KEY", description: "Required if using S3" },
      { name: "CLOUDFLARE_R2_ACCESS_KEY_ID", description: "Required if using R2" },
      { name: "CLOUDFLARE_R2_SECRET_ACCESS_KEY", description: "Required if using R2" },
      { name: "CLOUDFLARE_R2_ENDPOINT", description: "Required if using R2" },
      { name: "CLOUDFLARE_R2_BUCKET_NAME", description: "Required if using R2" },
      { name: "CLOUDFLARE_R2_PUBLIC_DEV_URL", description: "Required if using R2" },
    ],
    features: [
      "Multi-provider support: AWS S3 and Cloudflare R2",
      "Drag-and-drop uploads with 5 visual variants",
      "Real-time upload progress tracking via XHR",
      "File management (track, list, delete) with presigned URLs",
      "Full TypeScript support with Prisma DB integration",
    ],
    whenToUse: "Apps requiring secure file uploads, multi-cloud storage, or file management dashboards.",
    whenNotToUse: "Local-only storage, or projects choosing UploadThing (use UploadThing SDK directly).",
    filesAdded: [
      "/categories, /file-storage",
      "/api/s3/upload, /api/s3/delete, /api/r2/upload, /api/r2/delete",
      "/api/v1/categories/*, /api/v1/files, /api/v1/files/stats",
      "Components: Dropzone.tsx, ErrorDisplay.tsx + management UI",
      "Prisma: File, StorageProvider, Category models",
    ],
  },
  {
    slug: "mdx-blog",
    name: "MDX Blog",
    tagline: "File-based blog with MDX, syntax highlighting, and full SEO.",
    category: "content",
    categoryLabel: "Content",
    install: "pnpm dlx shadcn@latest add https://ui-components.desishub.com/r/mdx-blog.json",
    blogUrl: "https://jb.desishub.com/components/mdx-blog-component",
    prerequisites: ["Next.js with Tailwind CSS"],
    features: [
      "/blog listing + /blog/[slug] detail pages with prev/next nav",
      "MDX content rendering with rehype-pretty-code syntax highlighting",
      "Copy-to-clipboard on all code blocks",
      "Auto-generated SEO metadata (OpenGraph, Twitter, JSON-LD) per post",
      "3 sample blog posts as reference material",
    ],
    whenToUse: "Developer portfolios, product blogs, docs sites with code examples, teaching platforms.",
    whenNotToUse: "Projects needing comments, user-generated content, auth-gated content, or a CMS dashboard.",
    filesAdded: [
      "/blog, /blog/[slug]",
      "components/mdx.tsx, copy-button.tsx, post-item.tsx",
      "data/blog.ts, types/blog.ts",
      "content/blog/ — 3 sample .mdx files",
    ],
  },
  {
    slug: "scalar-api-docs",
    name: "Scalar API Docs",
    tagline: "Beautiful, interactive API docs deployed in 30 seconds.",
    category: "api",
    categoryLabel: "API",
    install: "pnpm dlx shadcn@latest add https://ui-components.desishub.com/r/scalar-api-docs.json",
    blogUrl: "https://jb.desishub.com/components/scalar-api-docs-component",
    prerequisites: ["Initialized Next.js project"],
    features: [
      "3 REST endpoints (Products, Categories, Users) with GET all + GET by ID",
      "Full OpenAPI 3.0.3 spec with schemas, examples, descriptions",
      "Scalar API Reference UI deployed at /api-docs",
      "Dummy data for immediate testing",
      "Auto-installs @scalar/nextjs-api-reference and openapi-types",
    ],
    whenToUse: "API prototyping, frontend dev with working endpoints, learning REST, hackathons, client demos.",
    whenNotToUse: "Custom auth schemes or non-REST APIs (GraphQL, tRPC).",
    filesAdded: [
      "app/api-docs/route.ts (Scalar UI)",
      "app/api/openapi/route.ts (OpenAPI JSON)",
      "app/api/products/, /categories/, /users/ — list + detail",
      "data/openapi.ts, data/dummy.ts",
    ],
  },
  {
    slug: "dgateway-shop",
    name: "DGateway Shop",
    tagline: "E-commerce + Mobile Money + Stripe — built for African markets.",
    category: "commerce",
    categoryLabel: "Commerce",
    install: "pnpm dlx shadcn@latest add https://ui-components.desishub.com/r/dgateway-shop.json",
    blogUrl: "https://jb.desishub.com/components/dgateway-shop-component",
    prerequisites: ["Next.js App Router", "DGateway account with API credentials"],
    envVars: [
      { name: "DGATEWAY_API_URL", description: "DGateway API endpoint (e.g. https://dgatewayapi.desispay.com)" },
      { name: "DGATEWAY_API_KEY", description: "API auth key from DGateway Dashboard" },
    ],
    features: [
      "Product catalog at /shop with sample products",
      "Cart with persistent localStorage and floating cart drawer",
      "Two payment methods: Mobile Money (UGX) + Stripe (USD)",
      "Real-time payment status polling with success/failure screens",
      "Auto-installs zustand, @stripe/react-stripe-js, @stripe/stripe-js",
    ],
    whenToUse: "African market payments, multi-currency (UGX + USD), marketplaces targeting mobile money users.",
    whenNotToUse: "Complex inventory, subscriptions, or Stripe-only markets (use Stripe UI instead).",
    filesAdded: [
      "/shop, /checkout",
      "/api/checkout (POST), /api/checkout/status (POST)",
      "components/cart-drawer.tsx",
      "lib/dgateway.ts, lib/cart-store.ts",
      "data/shop-products.ts",
    ],
  },
  {
    slug: "searchable-select",
    name: "Searchable Select",
    tagline: "Filterable dropdown with type-to-search and optional descriptions.",
    category: "forms",
    categoryLabel: "Forms",
    install: "pnpm dlx shadcn@latest add https://jb.desishub.com/r/searchable-select.json",
    blogUrl: "https://jb.desishub.com/components/searchable-select-component",
    prerequisites: ["React", "shadcn/ui"],
    features: [
      "Searchable dropdown to filter through options",
      "Clear button to reset selected value",
      "Optional description text per option",
      "Type-to-search and filter available choices",
      "Handles value selection and change callbacks",
    ],
    whenToUse: "Selects with 10+ options or where users benefit from type-to-filter (countries, tags, lookups).",
    whenNotToUse: "Simple 2–3 item selects (use shadcn Select), or multi-select scenarios.",
    filesAdded: ["searchable-select.tsx (location depends on install target)"],
  },
  /* ──────────────────────────────────────────────
   * Hero sections — community-curated landing heroes
   * ────────────────────────────────────────────── */
  {
    slug: "hero-spiral-background",
    name: "Spiral Background Hero",
    tagline: "A hero section with a golden spiral background — eye-catching for landing pages.",
    category: "hero",
    categoryLabel: "Hero section",
    install: "npx shadcn@latest add @ncdai/hero-01",
    source: "ncdai",
    sourceLabel: "ncdai · 21st.dev",
    features: [
      "Golden ratio spiral SVG backdrop",
      "Centered headline + sub + CTA stack",
      "Light + dark mode aware",
      "Drop-in replacement for any hero block",
    ],
    whenToUse: "Marketing landing pages where you want a distinctive, premium-feeling hero with mathematical/geometric energy.",
    whenNotToUse: "Dashboard apps or anywhere a busy backdrop would distract from the actual UI.",
  },
  {
    slug: "hero-115-ring-backdrop",
    name: "Hero 115 — Centered Ring Backdrop",
    tagline: "Centered hero with concentric ring decoration, leading icon, headline, supporting text, CTA, byline, and capped hero image.",
    category: "hero",
    categoryLabel: "Hero section",
    install: "pnpm dlx shadcn add @shadcnblocks/hero115",
    source: "shadcnblocks",
    sourceLabel: "shadcnblocks",
    features: [
      "Concentric ring decoration behind the copy",
      "Leading icon slot for product mark / logo",
      "Headline + supporting paragraph + primary CTA",
      "Optional byline (small text)",
      "Capped hero image area below the copy",
    ],
    whenToUse: "Product launches, app landing pages, anywhere you need a clean centered hero with a single focused CTA.",
    whenNotToUse: "Two-column hero layouts (with hero image on the right) — this one is centered.",
  },
  {
    slug: "hero-marketing-with-navbar",
    name: "Marketing Hero with Navbar",
    tagline: "Modern marketing hero section bundled with a fully styled navbar above it.",
    category: "hero",
    categoryLabel: "Hero section",
    install: "npx shadcn@latest add https://21st.dev/r/meschacirung/hero-section-2",
    source: "21st.dev",
    sourceLabel: "meschacirung · 21st.dev",
    features: [
      "Includes a matching navbar component",
      "Modern marketing aesthetic — large headline + supporting copy",
      "Primary + secondary CTA pair",
      "Mobile responsive out of the box",
    ],
    whenToUse: "Marketing sites that need both nav and hero in one consistent design — typically the public-facing landing page.",
    whenNotToUse: "If your project already has a custom navbar — you'd want the standalone hero variant instead.",
  },
  {
    slug: "hero-saas",
    name: "SaaS Hero",
    tagline: "Modern SaaS hero section — built for startups launching a product.",
    category: "hero",
    categoryLabel: "Hero section",
    install: "npx shadcn@latest add https://21st.dev/r/meschacirung/hero-section-1",
    source: "21st.dev",
    sourceLabel: "meschacirung · 21st.dev",
    features: [
      "Bold headline optimized for product positioning",
      "Sub-text, primary CTA, and optional secondary action",
      "Designed for SaaS conversion patterns",
      "Light + dark mode aware",
    ],
    whenToUse: "SaaS product landing pages where the hero needs to communicate value fast and drive sign-ups.",
    whenNotToUse: "Agency / portfolio sites — those have different conversion patterns.",
  },
  {
    slug: "hero-power-section",
    name: "Beautiful Power Hero",
    tagline: "Bold, dramatic hero section for product launches and rebrands.",
    category: "hero",
    categoryLabel: "Hero section",
    install: "npx shadcn@latest add https://21st.dev/r/mikolajdobrucki/hero-section",
    source: "21st.dev",
    sourceLabel: "mikolajdobrucki · 21st.dev",
    features: [
      "Striking visual treatment — big type, generous whitespace",
      "Designed to feel premium and editorial",
      "Single-column centered layout",
    ],
    whenToUse: "When you want the hero to do most of the storytelling — product launches, brand pages, manifestos.",
    whenNotToUse: "Information-dense pages where readers need to scan multiple sections quickly.",
  },
  {
    slug: "hero-agency",
    name: "Agency Hero",
    tagline: "Clean agency hero designed for SaaS and startup websites — bold headline, gradient background, trust badges, client logos.",
    category: "hero",
    categoryLabel: "Hero section",
    install: "pnpm dlx shadcn@latest add @shadcn-space/hero-01",
    source: "shadcn-space",
    sourceLabel: "shadcn-space",
    features: [
      "Bold conversion-focused headline",
      "Subtle gradient background",
      "Trust badges row",
      "Client logo strip",
      "High-converting primary CTA + secondary action",
    ],
    whenToUse: "Lead-generation pages: agency homepages, B2B SaaS, services landing pages, anywhere you need social proof + CTA above the fold.",
    whenNotToUse: "Internal app dashboards or content-first pages (blogs, docs).",
  },

  {
    slug: "zustand-cart",
    name: "Zustand Cart",
    tagline: "Client-side cart with localStorage persistence and drawer UI.",
    category: "commerce",
    categoryLabel: "Commerce",
    install: "pnpm dlx shadcn@latest add https://jb.desishub.com/r/zustand-cart.json",
    blogUrl: "https://jb.desishub.com/components/zustand-cart-component",
    prerequisites: ["React/Next.js with Tailwind", "shadcn/ui Button", "lucide-react"],
    features: [
      "Responsive product grid with images, descriptions, pricing",
      "Cart state with add/remove/quantity adjustment",
      "Floating cart panel with totals and checkout options",
      "Auto-persists cart to localStorage",
      "Reusable sub-components: ProductCard, ProductListing, Cart",
    ],
    whenToUse: "E-commerce sites needing client-side cart management with persistent storage. Install BEFORE Stripe UI.",
    whenNotToUse: "Server-side carts requiring real-time inventory sync or cross-device cart sharing.",
    filesAdded: [
      "use-cart-store.ts (Zustand hook)",
      "product-card.tsx, product-listing.tsx, cart.tsx",
      "zustand-cart.tsx (wrapper)",
      "index.ts (barrel export)",
    ],
  },
  {
    slug: "ecommerce-ui",
    name: "Ecommerce UI Primitives",
    tagline: "Rating stars, quantity selector, and price display with currency and discount support.",
    category: "commerce",
    categoryLabel: "Commerce",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/ecommerce-ui.json",
    features: [
      "Rating component with keyboard navigation, radio group ARIA, and hover preview",
      "Quantity selector with connected minus/plus buttons, min/max bounds, and disabled state",
      "Price display with currency formatting, compare-at strikethrough, and discount badge",
    ],
    whenToUse: "E-commerce product pages, catalog listings, and cart interfaces needing reusable pricing and interaction primitives.",
    whenNotToUse: "Simple static price labels or non-commerce contexts where these primitives aren't needed.",
  },
  {
    slug: "ecommerce-product",
    name: "Product Card & Grid",
    tagline: "Product card with image, price, rating, badge overlay, add-to-cart, and responsive grid with search and sort.",
    category: "commerce",
    categoryLabel: "Commerce",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/ecommerce-product.json",
    features: [
      "Product card with image hover zoom, badge overlays, and quick-add overlay on hover",
      "Responsive grid (2→3→4 columns) with search filtering and sort dropdown",
      "Skeleton loading state and empty state for no results",
      "Mobile: always-visible add-to-cart button below fold",
    ],
    whenToUse: "Product listing pages, catalogs, and storefronts needing a polished shopping experience.",
    whenNotToUse: "Simple text-only item lists, admin dashboards, or non-ecommerce contexts.",
  },
  {
    slug: "saas-subscription",
    name: "Subscription Status & Usage Meter",
    tagline: "Current subscription plan card with status, renewal, and upgrade actions, plus usage progress bars for API, storage, or seats.",
    category: "saas",
    categoryLabel: "SaaS",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/saas-subscription.json",
    features: [
      "Subscription plan card with status badge (active, past_due, canceled, trialing, incomplete)",
      "Renewal and trial end dates with contextual status messages",
      "Usage progress bars with automatic color thresholds (75% amber, 90% red)",
      "Manage and Upgrade action buttons in footer",
    ],
    whenToUse: "SaaS dashboard settings pages, account management, and billing sections.",
    whenNotToUse: "Consumer apps without subscriptions or metered usage.",
  },
  {
    slug: "saas-billing",
    name: "SaaS Billing: Pricing, Comparison & History",
    tagline: "Pricing tier cards with feature lists, side-by-side plan comparison table, and billing/invoice history list.",
    category: "saas",
    categoryLabel: "SaaS",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/saas-billing.json",
    features: [
      "Pricing tier cards with popular badge, feature check/x list, and CTA",
      "Feature comparison table with category sections, sticky first column with shadow",
      "Billing history list with invoice status badges per item and PDF download",
      "Empty states for all components when no data is provided",
    ],
    whenToUse: "SaaS landing pages (pricing section), account billing settings, admin portals.",
    whenNotToUse: "Simple flat-rate single-plan pricing or non-SaaS products.",
  },
  {
    slug: "saas-management",
    name: "SaaS Management: API Tokens",
    tagline: "API token manager with create dialog, scope selection, copy to clipboard, and revoke actions.",
    category: "saas",
    categoryLabel: "SaaS",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/saas-management.json",
    features: [
      "Token list with prefix display, copy-to-clipboard with 2-second feedback, and revoke button",
      "Create token dialog with scope selection (read/write per resource + admin)",
      "Newly-created token banner with one-time copy warning",
      "Empty state with guided CTA for first token creation",
    ],
    whenToUse: "SaaS developer portals, API management dashboards, and account settings pages.",
    whenNotToUse: "Consumer apps without API access or token-based auth.",
  },
  /* ──────────────────────────────────────────────
   * VibeKit in-house registry — productivity & cross-cutting UI
   * Hosted at vibekit.desishub.com/r/{slug}.json
   * ────────────────────────────────────────────── */
  {
    slug: "kanban-board",
    name: "Kanban Board",
    tagline: "Drag-and-drop board with column management, card creation, and swimlanes.",
    category: "productivity",
    categoryLabel: "Productivity",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/kanban-board.json",
    prerequisites: ["React 18+", "shadcn/ui base components", "dnd-kit (installed automatically)"],
    features: [
      "Drag-and-drop between columns with keyboard accessibility (dnd-kit)",
      "Add, rename, and delete columns inline",
      "Card creation dialog with title, description, and label",
      "Drag overlay preview with rotation feedback",
      "Controlled component — columns and onColumnsChange handler",
    ],
    whenToUse: "CRM pipelines, project management, content calendars, hiring boards, lightweight task trackers.",
    whenNotToUse: "Linear-style nested tasks or Gantt-style timelines — use a dedicated project management library.",
  },
  {
    slug: "rich-text-editor",
    name: "Rich Text Editor",
    tagline: "Tiptap-powered editor with toolbar, image, link, and placeholder support.",
    category: "content",
    categoryLabel: "Content",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/rich-text-editor.json",
    prerequisites: ["React 18+", "shadcn/ui base components", "@tiptap/react (installed automatically)"],
    features: [
      "Formatting toolbar (bold, italic, headings, lists, code block, quote)",
      "Image and link extensions out of the box",
      "Placeholder text and controlled HTML output",
      "Built on Tiptap StarterKit — extend with any Tiptap extension",
    ],
    whenToUse: "Notes, blog post editors, messaging composers, internal docs, knowledge bases.",
    whenNotToUse: "Markdown-only contexts (use the MDX Blog) or collaborative real-time editors (use Yjs directly).",
  },
  {
    slug: "org-team-ui",
    name: "Organization & Team UI",
    tagline: "Team management with member directory, invites, role-based access, and org settings.",
    category: "team",
    categoryLabel: "Team",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/org-team-ui.json",
    prerequisites: ["shadcn/ui base components (avatar, button, card, etc.)"],
    features: [
      "Member directory with avatars, names, roles, and last-active",
      "Invite-by-email dialog with role selection (admin / member / viewer)",
      "Pending invites list with resend and revoke actions",
      "Organization settings panel (name, slug, logo)",
    ],
    whenToUse: "Multi-tenant SaaS, agency portals, team workspaces, B2B apps that need RBAC and invites.",
    whenNotToUse: "Single-user apps or consumer products without team features.",
  },
  {
    slug: "charts-grid",
    name: "Charts & Dashboard Grid",
    tagline: "Responsive dashboard grid with bar, line, pie, and area charts on Recharts.",
    category: "data",
    categoryLabel: "Data",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/charts-grid.json",
    prerequisites: ["shadcn/ui (card, tabs, skeleton, button, badge)", "recharts (installed automatically)"],
    features: [
      "Bar, line, pie, and area chart variants",
      "Reusable ChartCard wrapper with title, description, and fullscreen toggle",
      "Responsive 1 → 2 → 4 column grid",
      "Loading skeletons and empty states baked in",
    ],
    whenToUse: "Analytics dashboards, reporting screens, KPI overviews, admin metrics.",
    whenNotToUse: "Single-chart pages — drop Recharts in directly instead of installing the full grid.",
  },
  {
    slug: "multi-step-form",
    name: "Multi-Step Form / Wizard",
    tagline: "Step-by-step form with progress indicator, per-step validation, and back/continue controls.",
    category: "forms",
    categoryLabel: "Forms",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/multi-step-form.json",
    prerequisites: ["React Hook Form", "Zod", "@hookform/resolvers (installed automatically)"],
    features: [
      "Step progress indicator with numbered badges",
      "React Hook Form + Zod validation per step",
      "Back / Continue / Submit navigation",
      "Skippable and required steps supported",
    ],
    whenToUse: "Onboarding wizards, checkout flows, surveys, complex sign-up forms.",
    whenNotToUse: "Single-screen forms — just use a normal Form component.",
  },
  {
    slug: "command-palette",
    name: "Command Palette",
    tagline: "⌘K palette with keyboard shortcuts, fuzzy search, and grouped actions.",
    category: "productivity",
    categoryLabel: "Productivity",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/command-palette.json",
    prerequisites: ["shadcn/ui Command + Dialog", "cmdk (installed automatically)"],
    features: [
      "⌘K / Ctrl-K global trigger",
      "Fuzzy search across actions, routes, and entities",
      "Grouped actions with icons and keyboard shortcuts",
      "Dialog-based modal using cmdk under the hood",
    ],
    whenToUse: "Dashboards with many routes, power-user apps, anywhere keyboard nav matters.",
    whenNotToUse: "Public marketing sites or apps with fewer than ~5 screens.",
  },
  {
    slug: "notification-center",
    name: "Notification Center",
    tagline: "Bell dropdown with real-time notifications, read/unread state, tabs, and clear-all.",
    category: "productivity",
    categoryLabel: "Productivity",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/notification-center.json",
    prerequisites: ["shadcn/ui (button, card, dropdown-menu, scroll-area, tabs, avatar, badge)"],
    features: [
      "Bell icon with unread badge count",
      "All / Unread tabs",
      "Avatar + actor + timestamp per item",
      "Mark-as-read and clear-all actions",
    ],
    whenToUse: "Apps with in-product notifications, alerts, activity feeds, or team mentions.",
    whenNotToUse: "Email-only notification flows or single-user apps with no events.",
  },
  {
    slug: "advanced-form-elements",
    name: "Advanced Form Elements",
    tagline: "Tags input and phone input with formatting, validation, and keyboard support.",
    category: "forms",
    categoryLabel: "Forms",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/advanced-form-elements.json",
    prerequisites: ["shadcn/ui (badge, button, input, label, popover, calendar, command)"],
    features: [
      "Tags input with badges, Enter to add, Backspace to remove",
      "Phone input with country picker and live formatting",
      "Keyboard accessible with proper ARIA roles",
      "Drop-in replacements inside React Hook Form",
    ],
    whenToUse: "Forms needing tag selection, phone numbers, or multi-value chip inputs.",
    whenNotToUse: "Simple text fields — use the shadcn Input component instead.",
  },
  {
    slug: "file-manager",
    name: "File Manager / Media Library",
    tagline: "Media library with grid/list views, preview dialog, upload button, and search.",
    category: "files",
    categoryLabel: "File storage",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/file-manager.json",
    prerequisites: ["shadcn/ui (button, card, dialog, input, badge)"],
    features: [
      "Grid + list view toggle",
      "File preview dialog with size, type, and uploaded date",
      "Search across file name and tags",
      "Upload button placeholder (wire to JB File Storage or UploadThing)",
    ],
    whenToUse: "Asset management screens, CMS media tabs, anywhere users browse and manage files.",
    whenNotToUse: "Apps that only need a single upload widget — install JB File Storage UI directly.",
  },
  {
    slug: "printable-templates",
    name: "Printable Templates",
    tagline: "Invoice, receipt, and report layouts with print-specific CSS and PDF export.",
    category: "documents",
    categoryLabel: "Documents",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/printable-templates.json",
    prerequisites: ["shadcn/ui (button, card, separator, table)"],
    features: [
      "Invoice, receipt, and report layouts",
      "Print stylesheet (page break, header/footer)",
      "Compatible with @react-pdf/renderer for PDF export",
      "Customizable issuer/customer/items props",
    ],
    whenToUse: "Anywhere the app needs invoices, receipts, or printable reports.",
    whenNotToUse: "Interactive dashboards — these are layout-only and meant for print/PDF output.",
  },
  /* ──────────────────────────────────────────────
   * Marketing primitives extracted from VibeKit public templates
   * ────────────────────────────────────────────── */
  {
    slug: "animated-counter",
    name: "Animated Counter",
    tagline: "Number stat that counts up from 0 to a target value when scrolled into view.",
    category: "animation",
    categoryLabel: "Animation",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/animated-counter.json",
    prerequisites: ["framer-motion (installed automatically)"],
    features: [
      "Counts up only after scrolling into view (useInView)",
      "Configurable duration, prefix, and suffix",
      "Locale-formatted numbers (12,345 not 12345)",
      "Single span — drops into any layout",
    ],
    whenToUse: "Marketing stat bands, dashboards highlighting milestone numbers, About / Press sections.",
    whenNotToUse: "Live counters that change after the initial reveal — use a state-driven number instead.",
  },
  {
    slug: "logo-marquee",
    name: "Logo Marquee",
    tagline: "Auto-scrolling 'trusted by' brand strip with pause-on-hover and edge fade.",
    category: "marketing",
    categoryLabel: "Marketing",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/logo-marquee.json",
    features: [
      "Auto-scrolling left or right with seamless loop",
      "Pause on hover (optional)",
      "Edge mask fade (optional)",
      "Accepts img src URLs, inline SVG nodes, or fallback text labels",
      "Configurable speed (seconds per loop)",
    ],
    whenToUse: "Marketing landing pages, hero 'trusted by' strips, integrations sections, social-proof bands.",
    whenNotToUse: "Static logo grids where movement would distract — use a plain flex layout.",
  },
  {
    slug: "alternating-timeline",
    name: "Alternating Timeline",
    tagline: "Vertical timeline with left/right alternating entries and scroll-driven opacity/scale.",
    category: "marketing",
    categoryLabel: "Marketing",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/alternating-timeline.json",
    prerequisites: ["framer-motion (installed automatically)"],
    features: [
      "Auto-alternating left/right layout per entry",
      "Scroll-driven opacity + scale on each item",
      "Optional image, meta line (date/role), title, description",
      "Center timeline rail with dot markers (desktop)",
      "Stacked single-column on mobile",
    ],
    whenToUse: "About pages, company history, roadmap timelines, product evolution stories.",
    whenNotToUse: "Linear feed lists or comment threads — use a simple list instead.",
  },
  {
    slug: "text-gradient-scroll",
    name: "Text Gradient Scroll",
    tagline: "Scroll-driven text reveal — paragraph fades word-by-word or letter-by-letter as the user scrolls.",
    category: "animation",
    categoryLabel: "Animation",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/text-gradient-scroll.json",
    prerequisites: ["framer-motion (installed automatically)"],
    features: [
      "Word-by-word OR letter-by-letter reveal granularity",
      "Three baseline opacity modes (none / soft / medium)",
      "Triggered by element's scroll position (useScroll)",
      "Drop-in <TextGradientScroll text=... /> — no setup",
    ],
    whenToUse: "Hero mission statements, manifesto sections, editorial brand pages.",
    whenNotToUse: "Critical product copy or anything that must be readable from the first frame — accessibility risk on slow scrolls.",
  },
  {
    slug: "blurred-orb",
    name: "Blurred Orb",
    tagline: "Gradient-blurred backdrop element — drop behind a hero or section for a soft glow accent.",
    category: "marketing",
    categoryLabel: "Marketing",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/blurred-orb.json",
    features: [
      "Primary / accent / muted variants using shadcn tokens",
      "Configurable size via className",
      "Override gradient via style prop for custom radial-gradients",
      "Aria-hidden + pointer-events-none — purely decorative",
    ],
    whenToUse: "Hero backdrops, behind feature cards, beside CTAs — anywhere a flat hero needs subtle depth.",
    whenNotToUse: "Information-dense interfaces where the blur would compete with content.",
  },
  {
    slug: "custom-cursor",
    name: "Custom Cursor",
    tagline: "Pointer-following animated cursor — dot + outline, hover grow, click squeeze, auto-hides on mobile.",
    category: "animation",
    categoryLabel: "Animation",
    install: "pnpm dlx shadcn@latest add https://vibekit.desishub.com/r/custom-cursor.json",
    prerequisites: ["framer-motion (installed automatically)"],
    features: [
      "Spring-physics follow with two layers (dot + outline ring)",
      "Mix-blend-difference for visibility on any background",
      "Hover grow on links, buttons, inputs, or any [data-cursor-hover] element",
      "Click squeeze feedback",
      "Auto-hides on screens under 768px (no touch-device cursor)",
    ],
    whenToUse: "Designer portfolios, agency sites, brand sites where a tactile cursor reinforces the aesthetic.",
    whenNotToUse: "App-style products, mobile-first audiences, accessibility-sensitive contexts. Add as a polish, not a default.",
  },
];

export const categories: { value: ComponentCategory | "all"; label: string }[] = [
  { value: "all", label: "All" },
  { value: "hero", label: "Hero" },
  { value: "marketing", label: "Marketing" },
  { value: "animation", label: "Animation" },
  { value: "auth", label: "Auth" },
  { value: "data", label: "Data" },
  { value: "commerce", label: "Commerce" },
  { value: "saas", label: "SaaS" },
  { value: "productivity", label: "Productivity" },
  { value: "team", label: "Team" },
  { value: "forms", label: "Forms" },
  { value: "content", label: "Content" },
  { value: "files", label: "Files" },
  { value: "documents", label: "Documents" },
  { value: "api", label: "API" },
];

export function getComponentBySlug(slug: string): JBComponent | undefined {
  return components.find((c) => c.slug === slug);
}

export function getAllComponentSlugs(): string[] {
  return components.map((c) => c.slug);
}
